import { useEffect } from "react";

// ───────────────────────────────────────────────────────────────
//  Rediseño · Federación Liga Simulada
//  Mockup estático en React. Dos direcciones (A: Refinado /
//  B: Élite), modo claro y oscuro. Todo el texto en español y los
//  códigos de posición (POR, DFC, MC, ED, DC…) se conservan.
//  Renderiza <RedisenoApp /> donde quieras previsualizarlo.
// ───────────────────────────────────────────────────────────────

export default function RedisenoApp() {
  useEffect(() => {
    if (!document.getElementById("fls-redesign-fonts")) {
      const link = document.createElement("link");
      link.id = "fls-redesign-fonts";
      link.rel = "stylesheet";
      link.href = "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@400;500;600;700;800&display=swap";
      document.head.appendChild(link);
    }
    if (!document.getElementById("fls-redesign-style")) {
      const st = document.createElement("style");
      st.id = "fls-redesign-style";
      st.textContent = ".fls-scr{flex:1;overflow:hidden;display:flex;flex-direction:column}";
      document.head.appendChild(st);
    }
  }, []);

  return (
      <div style={{minHeight: "100vh", background: "#e6e4df", padding: "52px 56px 80px", fontFamily: "'DM Sans',sans-serif", display: "flex", flexDirection: "column", gap: "50px"}}>
      
        
        <div style={{display: "flex", flexDirection: "column", gap: "10px", maxWidth: "760px"}}>
          <span style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "15px", letterSpacing: "3px", color: "#b8941f"}}>REDISEÑO · MOCKUP</span>
          <h1 style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "62px", lineHeight: "0.95", letterSpacing: "1px", color: "#1a1813"}}>Federación Liga Simulada</h1>
          <p style={{fontSize: "15px", lineHeight: "1.55", color: "#6b6555", maxWidth: "640px"}}>Dos direcciones para comparar, cada una en modo claro y oscuro. Se conserva el tema dorado, todo el texto en español y los códigos de posición (POR, DFC, MC, ED, DC…).</p>
        </div>
      
        
        
        
        <div style={{display: "flex", flexDirection: "column", gap: "8px"}}>
          <div style={{display: "flex", alignItems: "baseline", gap: "16px", flexWrap: "wrap"}}>
            <span style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "44px", letterSpacing: "1px", color: "#1a1813"}}>Dirección A</span>
            <span style={{fontSize: "11px", fontWeight: "800", letterSpacing: "1.5px", color: "#8a6d12", background: "#f6edcf", border: "1px solid #e7d89a", padding: "6px 12px", borderRadius: "20px"}}>REFINADO · ORO EDITORIAL</span>
          </div>
          <p style={{fontSize: "14px", lineHeight: "1.5", color: "#6b6555", maxWidth: "660px"}}>Aire y jerarquía tipográfica. Tarjetas blancas con bordes finísimos, el oro como acento medido y no como relleno. Sensación de federación premium y serena.</p>
        </div>
      
        <div style={{display: "flex", gap: "36px", flexWrap: "wrap", alignItems: "flex-start"}}>
      
          
          <div style={{display: "flex", flexDirection: "column", gap: "14px"}}>
            <div style={{display: "flex", alignItems: "center", gap: "10px"}}><span style={{fontSize: "13px", fontWeight: "700", color: "#3a352a"}}>Inicio</span><span style={{fontSize: "10px", fontWeight: "700", color: "#8a8474", background: "#fff", border: "1px solid #d8d3c6", padding: "3px 9px", borderRadius: "20px"}}>Claro</span></div>
            <div style={{width: "342px", height: "740px", background: "#faf9f5", borderRadius: "38px", border: "1px solid #d8d3c6", boxShadow: "0 30px 70px rgba(40,33,15,0.16),0 6px 16px rgba(0,0,0,0.06)", overflow: "hidden", display: "flex", flexDirection: "column", position: "relative"}}>
              <div style={{height: "46px", flexShrink: "0", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 26px", background: "#0f4a8a"}}>
                <span style={{fontSize: "13px", fontWeight: "700", color: "#fff"}}>9:41</span>
                <div style={{display: "flex", alignItems: "center", gap: "6px"}}><span style={{fontSize: "10px", fontWeight: "700", color: "#fff"}}>5G</span><div style={{width: "22px", height: "11px", border: "1.4px solid rgba(255,255,255,0.85)", borderRadius: "3px", display: "flex", alignItems: "center", padding: "1.5px"}}><div style={{width: "70%", height: "100%", background: "#fff", borderRadius: "1px"}}></div></div></div>
              </div>
              <div className="fls-scr">
                
                <div style={{background: "linear-gradient(158deg,#0f4a8a,#1a6bb5)", padding: "26px 22px 24px", display: "flex", flexDirection: "column", alignItems: "center", gap: "11px", position: "relative", overflow: "hidden"}}>
                  <div style={{position: "absolute", top: "-50px", right: "-40px", width: "150px", height: "150px", borderRadius: "50%", background: "rgba(255,255,255,0.06)"}}></div>
                  <div style={{width: "68px", height: "68px", borderRadius: "19px", background: "rgba(255,255,255,0.15)", border: "1.5px solid rgba(255,255,255,0.35)", backdropFilter: "blur(8px)", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 10px 30px rgba(0,0,0,0.28)", zIndex: "1"}}>
                    <span style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "27px", letterSpacing: "1px", color: "#fff"}}>FJ</span>
                  </div>
                  <div style={{textAlign: "center", zIndex: "1"}}>
                    <div style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "25px", letterSpacing: "1px", color: "#fff"}}>FC JAVIER</div>
                    <div style={{width: "34px", height: "2.5px", background: "#e9c45e", borderRadius: "2px", margin: "6px auto 7px"}}></div>
                    <div style={{fontSize: "11px", color: "rgba(255,255,255,0.72)"}}>2 competiciones activas · 150M</div>
                  </div>
                </div>
                
                <div style={{flex: "1", padding: "18px 16px", display: "flex", flexDirection: "column", gap: "10px", overflow: "hidden"}}>
                  <div style={{fontSize: "10px", fontWeight: "800", letterSpacing: "1px", color: "#a89f88", textTransform: "uppercase"}}>Mis competiciones</div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#fff", border: "1px solid #ece7da", borderRadius: "16px", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#f6edcf", border: "1px solid #ecdca0", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "21px"}}>🏆</div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "17px", letterSpacing: "0.4px", color: "#1a1813"}}>Liga Neo</div><div style={{fontSize: "10px", color: "#a89f88"}}>Ver mi alineación</div></div>
                    <span style={{fontSize: "20px", color: "#c9bfa6"}}>›</span>
                  </div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#fff", border: "1px solid #ece7da", borderRadius: "16px", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#eaf2fb", border: "1px solid #cfe1f5", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "21px"}}>⭐</div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "17px", letterSpacing: "0.4px", color: "#1a1813"}}>Champions EC</div><div style={{fontSize: "10px", color: "#a89f88"}}>Ver mi alineación</div></div>
                    <span style={{fontSize: "20px", color: "#c9bfa6"}}>›</span>
                  </div>
                  <div style={{fontSize: "10px", fontWeight: "800", letterSpacing: "1px", color: "#a89f88", textTransform: "uppercase", marginTop: "6px"}}>Más</div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#fff", border: "1px solid #ece7da", borderRadius: "16px", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#f3eee2", border: "1px solid #e6dcc6", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px", position: "relative"}}>📰<span style={{position: "absolute", top: "-5px", right: "-5px", minWidth: "19px", height: "19px", background: "#c0392b", color: "#fff", borderRadius: "50%", fontSize: "10px", fontWeight: "800", display: "flex", alignItems: "center", justifyContent: "center", border: "2px solid #fff"}}>3</span></div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "17px", letterSpacing: "0.4px", color: "#1a1813"}}>Noticias</div><div style={{fontSize: "10px", color: "#c0392b", fontWeight: "600"}}>¡Te mencionaron 3 veces!</div></div>
                    <span style={{fontSize: "20px", color: "#c9bfa6"}}>›</span>
                  </div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#fff", border: "1px solid #ece7da", borderRadius: "16px", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#f0ecf7", border: "1px solid #ddd2ee", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px"}}>🌍</div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "17px", letterSpacing: "0.4px", color: "#1a1813"}}>Mundial</div><div style={{fontSize: "10px", color: "#a89f88"}}>Selecciones nacionales</div></div>
                    <span style={{fontSize: "20px", color: "#c9bfa6"}}>›</span>
                  </div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#fff", border: "1px solid #ece7da", borderRadius: "16px", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#eaf2fb", border: "1px solid #cfe1f5", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px"}}>👕</div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "17px", letterSpacing: "0.4px", color: "#1a1813"}}>Mi Equipo</div><div style={{fontSize: "10px", color: "#a89f88"}}>Campo y plantilla</div></div>
                    <span style={{fontSize: "20px", color: "#c9bfa6"}}>›</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
      
          
          <div style={{display: "flex", flexDirection: "column", gap: "14px"}}>
            <div style={{display: "flex", alignItems: "center", gap: "10px"}}><span style={{fontSize: "13px", fontWeight: "700", color: "#3a352a"}}>Mi Equipo · Campo</span><span style={{fontSize: "10px", fontWeight: "700", color: "#8a8474", background: "#fff", border: "1px solid #d8d3c6", padding: "3px 9px", borderRadius: "20px"}}>Claro</span></div>
            <div style={{width: "342px", height: "740px", background: "#faf9f5", borderRadius: "38px", border: "1px solid #d8d3c6", boxShadow: "0 30px 70px rgba(40,33,15,0.16),0 6px 16px rgba(0,0,0,0.06)", overflow: "hidden", display: "flex", flexDirection: "column", position: "relative"}}>
              <div style={{height: "46px", flexShrink: "0", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 26px", background: "#faf9f5", borderBottom: "1px solid #efeade"}}>
                <span style={{fontSize: "13px", fontWeight: "700", color: "#1a1813"}}>9:41</span>
                <div style={{display: "flex", alignItems: "center", gap: "6px"}}><span style={{fontSize: "10px", fontWeight: "700", color: "#1a1813"}}>5G</span><div style={{width: "22px", height: "11px", border: "1.4px solid #1a1813", borderRadius: "3px", display: "flex", alignItems: "center", padding: "1.5px"}}><div style={{width: "70%", height: "100%", background: "#1a1813", borderRadius: "1px"}}></div></div></div>
              </div>
              <div className="fls-scr">
                
                <div style={{display: "flex", alignItems: "center", gap: "10px", padding: "12px 16px", borderBottom: "1px solid #efeade"}}>
                  <div style={{width: "32px", height: "32px", borderRadius: "10px", background: "#fff", border: "1px solid #e6dfce", display: "flex", alignItems: "center", justifyContent: "center", color: "#6b6555", fontSize: "18px"}}>‹</div>
                  <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue',sans-serif", fontSize: "18px", letterSpacing: "0.5px", color: "#1a1813", lineHeight: "1"}}>MI EQUIPO</div><div style={{fontSize: "10px", color: "#a89f88"}}>Alineación · Liga</div></div>
                  <div style={{fontSize: "11px", fontWeight: "800", color: "#8a6d12", background: "#f6edcf", border: "1px solid #e7d89a", padding: "5px 10px", borderRadius: "9px", fontFamily: "'DM Sans'"}}>4-3-3</div>
                  <div style={{width: "32px", height: "32px", borderRadius: "10px", background: "#fff", border: "1px solid #e6dfce", display: "flex", alignItems: "center", justifyContent: "center", color: "#6b6555", fontSize: "15px"}}>⚙</div>
                </div>
                <div style={{flex: "1", overflow: "hidden", padding: "12px 14px 0", display: "flex", flexDirection: "column", gap: "11px"}}>
                  
                  <div style={{position: "relative", borderRadius: "18px", overflow: "hidden", height: "392px", background: "linear-gradient(180deg,#16602f,#1d7a3d 50%,#16602f)", boxShadow: "inset 0 0 60px rgba(0,0,0,0.3),0 8px 22px rgba(0,0,0,0.18)"}}>
                    <div style={{position: "absolute", inset: "0", background: "repeating-linear-gradient(180deg,rgba(255,255,255,0.045) 0 33px,rgba(0,0,0,0.05) 33px 66px)"}}></div>
                    <div style={{position: "absolute", left: "14px", right: "14px", top: "50%", height: "1.5px", background: "rgba(255,255,255,0.4)"}}></div>
                    <div style={{position: "absolute", left: "50%", top: "50%", width: "86px", height: "86px", border: "1.5px solid rgba(255,255,255,0.4)", borderRadius: "50%", transform: "translate(-50%,-50%)"}}></div>
                    <div style={{position: "absolute", left: "50%", top: "0", transform: "translateX(-50%)", width: "120px", height: "46px", border: "1.5px solid rgba(255,255,255,0.32)", borderTop: "none", borderRadius: "0 0 8px 8px"}}></div>
                    <div style={{position: "absolute", left: "50%", bottom: "0", transform: "translateX(-50%)", width: "120px", height: "46px", border: "1.5px solid rgba(255,255,255,0.32)", borderBottom: "none", borderRadius: "8px 8px 0 0"}}></div>
                    
                    <div style={{position: "absolute", left: "50%", top: "87%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>89</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>COURTOIS</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>POR</div></div></div>
                    <div style={{position: "absolute", left: "80%", top: "69%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>85</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>HAKIMI</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>DFD</div></div></div>
                    <div style={{position: "absolute", left: "62%", top: "70%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>86</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>SALIBA</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>DFC</div></div></div>
                    <div style={{position: "absolute", left: "38%", top: "70%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>85</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>BASTONI</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>DFC</div></div></div>
                    <div style={{position: "absolute", left: "20%", top: "69%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>85</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>T. HDEZ</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>DFI</div></div></div>
                    <div style={{position: "absolute", left: "74%", top: "50%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>87</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>BELLINGHAM</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>MC</div></div></div>
                    <div style={{position: "absolute", left: "50%", top: "46%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "44px", height: "44px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid #e9c45e", boxShadow: "0 4px 12px rgba(0,0,0,0.45)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "17px", color: "#fff"}}>90</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>RODRI</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>MC</div></div></div>
                    <div style={{position: "absolute", left: "26%", top: "50%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>88</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>PEDRI</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>MC</div></div></div>
                    <div style={{position: "absolute", left: "80%", top: "26%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>87</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>SAKA</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>ED</div></div></div>
                    <div style={{position: "absolute", left: "50%", top: "16%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "44px", height: "44px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid #e9c45e", boxShadow: "0 4px 12px rgba(0,0,0,0.45)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "17px", color: "#fff"}}>91</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>HAALAND</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>DC</div></div></div>
                    <div style={{position: "absolute", left: "20%", top: "26%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2.5px solid rgba(255,255,255,0.92)", boxShadow: "0 4px 10px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#fff"}}>90</span></div><div style={{background: "rgba(20,15,6,0.82)", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#fff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>VINÍCIUS</div><div style={{fontSize: "7px", color: "#e9c45e", fontWeight: "700"}}>EI</div></div></div>
                  </div>
                  
                  <div style={{display: "flex", gap: "6px", overflow: "hidden"}}>
                    <div style={{fontSize: "11px", fontWeight: "800", color: "#15130d", background: "#f6edcf", border: "1.5px solid #d8b94a", padding: "5px 10px", borderRadius: "8px", fontFamily: "'DM Sans'"}}>4-3-3</div>
                    <div style={{fontSize: "11px", fontWeight: "700", color: "#8a8474", background: "#fff", border: "1px solid #e6dfce", padding: "5px 10px", borderRadius: "8px"}}>4-2-3-1</div>
                    <div style={{fontSize: "11px", fontWeight: "700", color: "#8a8474", background: "#fff", border: "1px solid #e6dfce", padding: "5px 10px", borderRadius: "8px"}}>4-4-2</div>
                    <div style={{fontSize: "11px", fontWeight: "700", color: "#8a8474", background: "#fff", border: "1px solid #e6dfce", padding: "5px 10px", borderRadius: "8px"}}>3-5-2</div>
                  </div>
                  
                  <div style={{background: "#fff", border: "1px solid #ece7da", borderRadius: "14px", padding: "11px 11px 13px", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{display: "flex", alignItems: "center", gap: "8px", marginBottom: "9px"}}><div style={{width: "3px", height: "14px", background: "#b8941f", borderRadius: "2px"}}></div><span style={{fontFamily: "'Bebas Neue'", fontSize: "13px", letterSpacing: "1.2px", color: "#1a1813"}}>BANCA</span><span style={{marginLeft: "auto", fontSize: "10px", fontWeight: "700", color: "#fff", background: "#1a6bb5", padding: "2px 8px", borderRadius: "20px"}}>4/7</span></div>
                    <div style={{display: "grid", gridTemplateColumns: "repeat(7,1fr)", gap: "6px"}}>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#f7f4ec", border: "1px solid #e6dfce", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2px solid #fff", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#fff"}}>86</span></div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#1a1813"}}>MAIGNAN</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#f7f4ec", border: "1px solid #e6dfce", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2px solid #fff", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#fff"}}>86</span></div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#1a1813"}}>DIAS</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#f7f4ec", border: "1px solid #e6dfce", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2px solid #fff", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#fff"}}>88</span></div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#1a1813"}}>VALVERDE</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#f7f4ec", border: "1px solid #e6dfce", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f4a8a)", border: "2px solid #fff", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#fff"}}>86</span></div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#1a1813"}}>MUSIALA</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#faf9f5", border: "1px dashed #d8d0bc", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", border: "1.5px dashed #cabf9f", display: "flex", alignItems: "center", justifyContent: "center", color: "#cabf9f", fontSize: "15px"}}>+</div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#b3ac9c"}}>SUB 5</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#faf9f5", border: "1px dashed #d8d0bc", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", border: "1.5px dashed #cabf9f", display: "flex", alignItems: "center", justifyContent: "center", color: "#cabf9f", fontSize: "15px"}}>+</div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#b3ac9c"}}>SUB 6</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#faf9f5", border: "1px dashed #d8d0bc", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", border: "1.5px dashed #cabf9f", display: "flex", alignItems: "center", justifyContent: "center", color: "#cabf9f", fontSize: "15px"}}>+</div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#b3ac9c"}}>SUB 7</div></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      
          
          <div style={{display: "flex", flexDirection: "column", gap: "14px"}}>
            <div style={{display: "flex", alignItems: "center", gap: "10px"}}><span style={{fontSize: "13px", fontWeight: "700", color: "#3a352a"}}>Mercado · Calculadora</span><span style={{fontSize: "10px", fontWeight: "700", color: "#8a8474", background: "#fff", border: "1px solid #d8d3c6", padding: "3px 9px", borderRadius: "20px"}}>Claro</span></div>
            <div style={{width: "342px", height: "740px", background: "#faf9f5", borderRadius: "38px", border: "1px solid #d8d3c6", boxShadow: "0 30px 70px rgba(40,33,15,0.16),0 6px 16px rgba(0,0,0,0.06)", overflow: "hidden", display: "flex", flexDirection: "column", position: "relative"}}>
              <div style={{height: "46px", flexShrink: "0", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 26px", background: "#1a3a5c"}}>
                <span style={{fontSize: "13px", fontWeight: "700", color: "#fff"}}>9:41</span>
                <div style={{display: "flex", alignItems: "center", gap: "6px"}}><span style={{fontSize: "10px", fontWeight: "700", color: "#fff"}}>5G</span><div style={{width: "22px", height: "11px", border: "1.4px solid rgba(255,255,255,0.85)", borderRadius: "3px", display: "flex", alignItems: "center", padding: "1.5px"}}><div style={{width: "70%", height: "100%", background: "#fff", borderRadius: "1px"}}></div></div></div>
              </div>
              <div className="fls-scr">
                <div style={{background: "#1a3a5c", padding: "13px 18px 15px", display: "flex", alignItems: "center", gap: "9px"}}>
                  <span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", letterSpacing: "0.8px", color: "#fff"}}>CALCULADORA DE MERCADO</span>
                  <span style={{marginLeft: "auto", fontSize: "9px", fontWeight: "700", color: "#1a3a5c", background: "#e9c45e", padding: "3px 9px", borderRadius: "20px"}}>ABIERTO</span>
                </div>
                <div style={{flex: "1", overflow: "hidden", padding: "14px 16px", display: "flex", flexDirection: "column", gap: "13px"}}>
                  
                  <div>
                    <div style={{display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px"}}><span style={{fontSize: "11px", fontWeight: "800", letterSpacing: "0.5px", color: "#c0392b", textTransform: "uppercase"}}>↑ Bajas (3/6)</span><span style={{fontSize: "10px", color: "#a89f88", fontFamily: "'DM Sans'"}}>Total: +52M</span></div>
                    <div style={{display: "flex", flexDirection: "column", gap: "6px"}}>
                      <div style={{display: "flex", alignItems: "center", gap: "7px", background: "#fff", border: "1px solid #ece7da", borderRadius: "11px", padding: "9px 11px"}}><span style={{fontSize: "10px", color: "#b3ac9c", fontFamily: "monospace"}}>1.</span><span style={{flex: "1", fontSize: "12px", fontWeight: "600", color: "#1a1813"}}>B. Saka</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1a1813", fontFamily: "monospace"}}>22M</span><span style={{fontSize: "9px", color: "#8a8474", background: "#f3eee2", padding: "2px 6px", borderRadius: "6px"}}>→ Real EC</span></div>
                      <div style={{display: "flex", alignItems: "center", gap: "7px", background: "#fff", border: "1px solid #ece7da", borderRadius: "11px", padding: "9px 11px"}}><span style={{fontSize: "10px", color: "#b3ac9c", fontFamily: "monospace"}}>2.</span><span style={{flex: "1", fontSize: "12px", fontWeight: "600", color: "#1a1813"}}>L. Digne</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1a1813", fontFamily: "monospace"}}>15.5M</span><span style={{fontSize: "9px", color: "#8a8474", background: "#f3eee2", padding: "2px 6px", borderRadius: "6px"}}>→ Inter</span></div>
                      <div style={{display: "flex", alignItems: "center", gap: "7px", background: "#fff", border: "1px solid #ece7da", borderRadius: "11px", padding: "9px 11px"}}><span style={{fontSize: "10px", color: "#b3ac9c", fontFamily: "monospace"}}>3.</span><span style={{flex: "1", fontSize: "12px", fontWeight: "600", color: "#1a1813"}}>N. Otamendi</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1a1813", fontFamily: "monospace"}}>14.5M</span><span style={{fontSize: "9px", color: "#b8941f", background: "#f6edcf", padding: "2px 6px", borderRadius: "6px"}}>⏳ → Ajax</span></div>
                    </div>
                  </div>
                  
                  <div>
                    <div style={{display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px"}}><span style={{fontSize: "11px", fontWeight: "800", letterSpacing: "0.5px", color: "#1f8a4c", textTransform: "uppercase"}}>↓ Altas (2/6)</span><span style={{fontSize: "10px", color: "#a89f88", fontFamily: "'DM Sans'"}}>Total: -40M</span></div>
                    <div style={{display: "flex", flexDirection: "column", gap: "6px"}}>
                      <div style={{display: "flex", alignItems: "center", gap: "7px", background: "#fff", border: "1px solid #ece7da", borderRadius: "11px", padding: "9px 11px"}}><span style={{fontSize: "10px", color: "#b3ac9c", fontFamily: "monospace"}}>1.</span><span style={{flex: "1", fontSize: "12px", fontWeight: "600", color: "#1a1813"}}>A. Baena</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1a1813", fontFamily: "monospace"}}>26M</span><span style={{fontSize: "9px", color: "#8a8474", background: "#f3eee2", padding: "2px 6px", borderRadius: "6px"}}>← Villa</span></div>
                      <div style={{display: "flex", alignItems: "center", gap: "7px", background: "#fff", border: "1px solid #ece7da", borderRadius: "11px", padding: "9px 11px"}}><span style={{fontSize: "10px", color: "#b3ac9c", fontFamily: "monospace"}}>2.</span><span style={{flex: "1", fontSize: "12px", fontWeight: "600", color: "#1a1813"}}>M. Asensio</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1a1813", fontFamily: "monospace"}}>14M</span><span style={{fontSize: "9px", color: "#8a8474", background: "#f3eee2", padding: "2px 6px", borderRadius: "6px"}}>← PSG</span></div>
                    </div>
                  </div>
                  
                  <div style={{background: "#fff", border: "1px solid #ece7da", borderRadius: "13px", padding: "13px 15px", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{display: "flex", justifyContent: "space-between", marginBottom: "5px"}}><span style={{fontSize: "11px", color: "#a89f88"}}>Presupuesto actual</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1a1813", fontFamily: "monospace"}}>150M</span></div>
                    <div style={{display: "flex", justifyContent: "space-between", marginBottom: "5px"}}><span style={{fontSize: "11px", color: "#c0392b"}}>+ Ingresos (bajas)</span><span style={{fontSize: "11px", fontWeight: "700", color: "#c0392b", fontFamily: "monospace"}}>+52M</span></div>
                    <div style={{display: "flex", justifyContent: "space-between", marginBottom: "9px"}}><span style={{fontSize: "11px", color: "#1f8a4c"}}>− Gasto (altas)</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1f8a4c", fontFamily: "monospace"}}>−40M</span></div>
                    <div style={{borderTop: "1px solid #ece7da", paddingTop: "9px", display: "flex", justifyContent: "space-between", alignItems: "center"}}><span style={{fontSize: "12px", fontWeight: "800", color: "#1a1813"}}>Saldo final</span><span style={{fontFamily: "'Bebas Neue'", fontSize: "20px", color: "#1f8a4c"}}>162M</span></div>
                  </div>
                  <button style={{border: "none", width: "100%", padding: "13px", borderRadius: "11px", background: "linear-gradient(180deg,#1a6bb5,#0f4a8a)", color: "#fff", fontFamily: "'Bebas Neue'", fontSize: "14px", letterSpacing: "1px", boxShadow: "0 6px 16px rgba(15,74,138,0.3)"}}>✓ FINALIZAR MERCADO</button>
                </div>
              </div>
            </div>
          </div>
      
          
          <div style={{display: "flex", flexDirection: "column", gap: "14px"}}>
            <div style={{display: "flex", alignItems: "center", gap: "10px"}}><span style={{fontSize: "13px", fontWeight: "700", color: "#3a352a"}}>Mundial · Grupos</span><span style={{fontSize: "10px", fontWeight: "700", color: "#8a8474", background: "#fff", border: "1px solid #d8d3c6", padding: "3px 9px", borderRadius: "20px"}}>Claro</span></div>
            <div style={{width: "342px", height: "740px", background: "#faf9f5", borderRadius: "38px", border: "1px solid #d8d3c6", boxShadow: "0 30px 70px rgba(40,33,15,0.16),0 6px 16px rgba(0,0,0,0.06)", overflow: "hidden", display: "flex", flexDirection: "column", position: "relative"}}>
              <div style={{height: "46px", flexShrink: "0", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 26px", background: "#4c1d95"}}>
                <span style={{fontSize: "13px", fontWeight: "700", color: "#fff"}}>9:41</span>
                <div style={{display: "flex", alignItems: "center", gap: "6px"}}><span style={{fontSize: "10px", fontWeight: "700", color: "#fff"}}>5G</span><div style={{width: "22px", height: "11px", border: "1.4px solid rgba(255,255,255,0.85)", borderRadius: "3px", display: "flex", alignItems: "center", padding: "1.5px"}}><div style={{width: "70%", height: "100%", background: "#fff", borderRadius: "1px"}}></div></div></div>
              </div>
              <div className="fls-scr">
                <div style={{background: "linear-gradient(135deg,#4c1d95,#7c3aed)", padding: "18px 18px 16px", display: "flex", alignItems: "center", gap: "11px"}}>
                  <div style={{width: "40px", height: "40px", borderRadius: "12px", background: "rgba(255,255,255,0.18)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px"}}>🌍</div>
                  <div><div style={{fontFamily: "'Bebas Neue'", fontSize: "20px", letterSpacing: "0.8px", color: "#fff", lineHeight: "1"}}>MUNDIAL</div><div style={{fontSize: "10px", color: "rgba(255,255,255,0.7)"}}>Selecciones nacionales</div></div>
                </div>
                
                <div style={{margin: "13px 16px 0", padding: "11px 13px", borderRadius: "13px", background: "#fff", border: "1px solid #ece7da", display: "flex", alignItems: "center", gap: "10px", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                  <span style={{display: "flex", alignItems: "center", gap: "5px", fontSize: "10px", fontWeight: "800", color: "#c0392b"}}><span style={{width: "7px", height: "7px", borderRadius: "50%", background: "#c0392b", display: "inline-block"}}></span>EN VIVO</span>
                  <span style={{flex: "1", fontSize: "12px", fontWeight: "700", color: "#1a1813"}}>ARGENTINA <span style={{color: "#b3ac9c", fontWeight: "600"}}>vs</span> FRANCIA</span>
                  <span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#1a1813"}}>2 – 1</span>
                </div>
                <div style={{flex: "1", overflow: "hidden", padding: "14px 16px", display: "flex", flexDirection: "column", gap: "10px"}}>
                  <div style={{display: "flex", alignItems: "center", gap: "8px"}}><div style={{width: "3px", height: "14px", background: "#7c3aed", borderRadius: "2px"}}></div><span style={{fontFamily: "'Bebas Neue'", fontSize: "15px", letterSpacing: "1px", color: "#1a1813"}}>GRUPO A</span></div>
                  <div style={{background: "#fff", border: "1px solid #ece7da", borderRadius: "14px", overflow: "hidden", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{display: "grid", gridTemplateColumns: "24px 1fr 28px 28px 34px", gap: "6px", padding: "9px 13px", background: "#f7f4ec", fontSize: "9px", fontWeight: "800", color: "#a89f88", letterSpacing: "0.5px"}}><span>#</span><span>SELECCIÓN</span><span style={{textAlign: "center"}}>PJ</span><span style={{textAlign: "center"}}>DG</span><span style={{textAlign: "center"}}>PTS</span></div>
                    <div style={{display: "grid", gridTemplateColumns: "24px 1fr 28px 28px 34px", gap: "6px", padding: "10px 13px", alignItems: "center", borderTop: "1px solid #f0ebdf"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "14px", color: "#b8941f"}}>1</span><span style={{fontSize: "12px", fontWeight: "700", color: "#1a1813"}}>Argentina</span><span style={{textAlign: "center", fontSize: "11px", color: "#6b6555", fontFamily: "monospace"}}>3</span><span style={{textAlign: "center", fontSize: "11px", color: "#1f8a4c", fontFamily: "monospace"}}>+5</span><span style={{textAlign: "center", fontFamily: "'Bebas Neue'", fontSize: "15px", color: "#1a1813"}}>9</span></div>
                    <div style={{display: "grid", gridTemplateColumns: "24px 1fr 28px 28px 34px", gap: "6px", padding: "10px 13px", alignItems: "center", borderTop: "1px solid #f0ebdf"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "14px", color: "#b8941f"}}>2</span><span style={{fontSize: "12px", fontWeight: "700", color: "#1a1813"}}>Francia</span><span style={{textAlign: "center", fontSize: "11px", color: "#6b6555", fontFamily: "monospace"}}>3</span><span style={{textAlign: "center", fontSize: "11px", color: "#1f8a4c", fontFamily: "monospace"}}>+2</span><span style={{textAlign: "center", fontFamily: "'Bebas Neue'", fontSize: "15px", color: "#1a1813"}}>6</span></div>
                    <div style={{display: "grid", gridTemplateColumns: "24px 1fr 28px 28px 34px", gap: "6px", padding: "10px 13px", alignItems: "center", borderTop: "1px solid #f0ebdf", opacity: "0.62"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "14px", color: "#b3ac9c"}}>3</span><span style={{fontSize: "12px", fontWeight: "700", color: "#1a1813"}}>España</span><span style={{textAlign: "center", fontSize: "11px", color: "#6b6555", fontFamily: "monospace"}}>3</span><span style={{textAlign: "center", fontSize: "11px", color: "#c0392b", fontFamily: "monospace"}}>−1</span><span style={{textAlign: "center", fontFamily: "'Bebas Neue'", fontSize: "15px", color: "#1a1813"}}>3</span></div>
                    <div style={{display: "grid", gridTemplateColumns: "24px 1fr 28px 28px 34px", gap: "6px", padding: "10px 13px", alignItems: "center", borderTop: "1px solid #f0ebdf", opacity: "0.62"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "14px", color: "#b3ac9c"}}>4</span><span style={{fontSize: "12px", fontWeight: "700", color: "#1a1813"}}>Mali</span><span style={{textAlign: "center", fontSize: "11px", color: "#6b6555", fontFamily: "monospace"}}>3</span><span style={{textAlign: "center", fontSize: "11px", color: "#c0392b", fontFamily: "monospace"}}>−6</span><span style={{textAlign: "center", fontFamily: "'Bebas Neue'", fontSize: "15px", color: "#1a1813"}}>0</span></div>
                  </div>
                  <div style={{display: "flex", alignItems: "center", gap: "8px", marginTop: "4px"}}><div style={{width: "3px", height: "14px", background: "#7c3aed", borderRadius: "2px"}}></div><span style={{fontFamily: "'Bebas Neue'", fontSize: "15px", letterSpacing: "1px", color: "#1a1813"}}>GOLEADORES</span></div>
                  <div style={{background: "#fff", border: "1px solid #ece7da", borderRadius: "14px", overflow: "hidden", boxShadow: "0 2px 10px rgba(40,33,15,0.04)"}}>
                    <div style={{display: "flex", alignItems: "center", gap: "11px", padding: "10px 13px"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "14px", color: "#b8941f", width: "14px"}}>1</span><div style={{width: "30px", height: "30px", borderRadius: "50%", background: "linear-gradient(140deg,#75aadb,#2e6cb0)", border: "2px solid #fff", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#fff"}}>L</div><span style={{flex: "1", fontSize: "12px", fontWeight: "700", color: "#1a1813"}}>L. Messi</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1a1813"}}>5 ⚽</span></div>
                    <div style={{display: "flex", alignItems: "center", gap: "11px", padding: "10px 13px", borderTop: "1px solid #f0ebdf"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "14px", color: "#a89f88", width: "14px"}}>2</span><div style={{width: "30px", height: "30px", borderRadius: "50%", background: "linear-gradient(140deg,#4f6fae,#2b3f7a)", border: "2px solid #fff", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#fff"}}>K</div><span style={{flex: "1", fontSize: "12px", fontWeight: "700", color: "#1a1813"}}>K. Mbappé</span><span style={{fontSize: "11px", fontWeight: "700", color: "#1a1813"}}>4 ⚽</span></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      
        </div>
      
        
        <div style={{display: "flex", flexDirection: "column", gap: "18px"}}>
          <p style={{fontSize: "14px", lineHeight: "1.5", color: "#6b6555", maxWidth: "660px"}}>El mismo sistema en <strong style={{color: "#1a1813"}}>modo oscuro</strong>: carbón cálido, bordes finos y el mismo oro editorial.</p>
          <div style={{display: "flex", gap: "36px", flexWrap: "wrap", alignItems: "flex-start"}}>
            <div style={{display: "flex", flexDirection: "column", gap: "14px"}}>
              <div style={{display: "flex", alignItems: "center", gap: "10px"}}><span style={{fontSize: "13px", fontWeight: "700", color: "#3a352a"}}>Inicio</span><span style={{fontSize: "10px", fontWeight: "700", color: "#3a352a", background: "#1a1813", padding: "3px 9px", borderRadius: "20px"}}>Oscuro</span></div>
              <div style={{width: "342px", height: "740px", background: "#100f11", borderRadius: "38px", border: "1px solid #2a2722", boxShadow: "0 30px 70px rgba(0,0,0,0.32),0 6px 16px rgba(0,0,0,0.2)", overflow: "hidden", display: "flex", flexDirection: "column", position: "relative"}}>
                <div style={{height: "46px", flexShrink: "0", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 26px", background: "#0f4a8a"}}>
                  <span style={{fontSize: "13px", fontWeight: "700", color: "#fff"}}>9:41</span>
                  <div style={{display: "flex", alignItems: "center", gap: "6px"}}><span style={{fontSize: "10px", fontWeight: "700", color: "#fff"}}>5G</span><div style={{width: "22px", height: "11px", border: "1.4px solid rgba(255,255,255,0.85)", borderRadius: "3px", display: "flex", alignItems: "center", padding: "1.5px"}}><div style={{width: "70%", height: "100%", background: "#fff", borderRadius: "1px"}}></div></div></div>
                </div>
                <div className="fls-scr">
                  <div style={{background: "linear-gradient(158deg,#0f4a8a,#1a6bb5)", padding: "26px 22px 24px", display: "flex", flexDirection: "column", alignItems: "center", gap: "11px", position: "relative", overflow: "hidden"}}>
                    <div style={{position: "absolute", top: "-50px", right: "-40px", width: "150px", height: "150px", borderRadius: "50%", background: "rgba(255,255,255,0.06)"}}></div>
                    <div style={{width: "68px", height: "68px", borderRadius: "19px", background: "rgba(255,255,255,0.15)", border: "1.5px solid rgba(255,255,255,0.35)", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 10px 30px rgba(0,0,0,0.35)", zIndex: "1"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "27px", letterSpacing: "1px", color: "#fff"}}>FJ</span></div>
                    <div style={{textAlign: "center", zIndex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "25px", letterSpacing: "1px", color: "#fff"}}>FC JAVIER</div><div style={{width: "34px", height: "2.5px", background: "#e9c45e", borderRadius: "2px", margin: "6px auto 7px"}}></div><div style={{fontSize: "11px", color: "rgba(255,255,255,0.72)"}}>2 competiciones activas · 150M</div></div>
                  </div>
                  <div style={{flex: "1", padding: "18px 16px", display: "flex", flexDirection: "column", gap: "10px", overflow: "hidden"}}>
                    <div style={{fontSize: "10px", fontWeight: "800", letterSpacing: "1px", color: "#6b6453", textTransform: "uppercase"}}>Mis competiciones</div>
                    <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#1a181c", border: "1px solid #2a2722", borderRadius: "16px"}}>
                      <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#2a2414", border: "1px solid #4a3f1d", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "21px"}}>🏆</div>
                      <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "17px", letterSpacing: "0.4px", color: "#f1ece0"}}>Liga Neo</div><div style={{fontSize: "10px", color: "#8f897b"}}>Ver mi alineación</div></div><span style={{fontSize: "20px", color: "#5a554c"}}>›</span>
                    </div>
                    <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#1a181c", border: "1px solid #2a2722", borderRadius: "16px"}}>
                      <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#152436", border: "1px solid #244563", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "21px"}}>⭐</div>
                      <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "17px", letterSpacing: "0.4px", color: "#f1ece0"}}>Champions EC</div><div style={{fontSize: "10px", color: "#8f897b"}}>Ver mi alineación</div></div><span style={{fontSize: "20px", color: "#5a554c"}}>›</span>
                    </div>
                    <div style={{fontSize: "10px", fontWeight: "800", letterSpacing: "1px", color: "#6b6453", textTransform: "uppercase", marginTop: "6px"}}>Más</div>
                    <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#1a181c", border: "1px solid #2a2722", borderRadius: "16px"}}>
                      <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#231f1a", border: "1px solid #38322a", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px", position: "relative"}}>📰<span style={{position: "absolute", top: "-5px", right: "-5px", minWidth: "19px", height: "19px", background: "#c0392b", color: "#fff", borderRadius: "50%", fontSize: "10px", fontWeight: "800", display: "flex", alignItems: "center", justifyContent: "center", border: "2px solid #100f11"}}>3</span></div>
                      <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "17px", letterSpacing: "0.4px", color: "#f1ece0"}}>Noticias</div><div style={{fontSize: "10px", fontWeight: "600", color: "#e07b6e"}}>¡Te mencionaron 3 veces!</div></div><span style={{fontSize: "20px", color: "#5a554c"}}>›</span>
                    </div>
                    <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#1a181c", border: "1px solid #2a2722", borderRadius: "16px"}}>
                      <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#1f1a2b", border: "1px solid #362d4d", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px"}}>🌍</div>
                      <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "17px", letterSpacing: "0.4px", color: "#f1ece0"}}>Mundial</div><div style={{fontSize: "10px", color: "#8f897b"}}>Selecciones nacionales</div></div><span style={{fontSize: "20px", color: "#5a554c"}}>›</span>
                    </div>
                    <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#1a181c", border: "1px solid #2a2722", borderRadius: "16px"}}>
                      <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#152436", border: "1px solid #244563", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px"}}>👕</div>
                      <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "17px", letterSpacing: "0.4px", color: "#f1ece0"}}>Mi Equipo</div><div style={{fontSize: "10px", color: "#8f897b"}}>Campo y plantilla</div></div><span style={{fontSize: "20px", color: "#5a554c"}}>›</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      
        
        
        
        <div style={{display: "flex", flexDirection: "column", gap: "8px", marginTop: "14px"}}>
          <div style={{display: "flex", alignItems: "baseline", gap: "16px", flexWrap: "wrap"}}>
            <span style={{fontFamily: "'Bebas Neue'", fontSize: "44px", letterSpacing: "1px", color: "#1a1813"}}>Dirección B</span>
            <span style={{fontSize: "11px", fontWeight: "800", letterSpacing: "1.5px", color: "#3a2c08", background: "linear-gradient(90deg,#f6dd92,#d4af4a)", border: "1px solid #c79f3a", padding: "6px 12px", borderRadius: "20px"}}>ÉLITE · ORO METÁLICO</span>
          </div>
          <p style={{fontSize: "14px", lineHeight: "1.5", color: "#6b6555", maxWidth: "660px"}}>FUT-premium. Negro por capas, oro foil y brillos sutiles. Energía de juego, números dorados y tarjetas con sensación coleccionable.</p>
        </div>
      
        <div style={{display: "flex", gap: "36px", flexWrap: "wrap", alignItems: "flex-start"}}>
      
          
          <div style={{display: "flex", flexDirection: "column", gap: "14px"}}>
            <div style={{display: "flex", alignItems: "center", gap: "10px"}}><span style={{fontSize: "13px", fontWeight: "700", color: "#3a352a"}}>Inicio</span><span style={{fontSize: "10px", fontWeight: "700", color: "#e9c45e", background: "#1a1813", padding: "3px 9px", borderRadius: "20px"}}>Oscuro</span></div>
            <div style={{width: "342px", height: "740px", background: "#0a0a0c", borderRadius: "38px", border: "1px solid #26242c", boxShadow: "0 30px 70px rgba(0,0,0,0.4),0 0 0 1px rgba(236,200,98,0.04)", overflow: "hidden", display: "flex", flexDirection: "column", position: "relative"}}>
              <div style={{height: "46px", flexShrink: "0", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 26px", background: "#0a1626"}}>
                <span style={{fontSize: "13px", fontWeight: "700", color: "#fff"}}>9:41</span>
                <div style={{display: "flex", alignItems: "center", gap: "6px"}}><span style={{fontSize: "10px", fontWeight: "700", color: "#fff"}}>5G</span><div style={{width: "22px", height: "11px", border: "1.4px solid rgba(255,255,255,0.85)", borderRadius: "3px", display: "flex", alignItems: "center", padding: "1.5px"}}><div style={{width: "70%", height: "100%", background: "#fff", borderRadius: "1px"}}></div></div></div>
              </div>
              <div className="fls-scr">
                
                <div style={{background: "linear-gradient(160deg,#123a63,#0a1626 78%)", padding: "28px 22px 26px", display: "flex", flexDirection: "column", alignItems: "center", gap: "11px", position: "relative", overflow: "hidden"}}>
                  <div style={{position: "absolute", top: "-60px", left: "50%", transform: "translateX(-50%)", width: "240px", height: "160px", background: "radial-gradient(ellipse,rgba(236,200,98,0.12),transparent 70%)"}}></div>
                  <div style={{width: "70px", height: "70px", borderRadius: "19px", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "1.5px solid", borderImage: "linear-gradient(140deg,#f6dd92,#a9842c) 1", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 10px 30px rgba(0,0,0,0.5),0 0 24px rgba(236,200,98,0.18)", zIndex: "1"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "28px", letterSpacing: "1px", color: "#fff"}}>FJ</span></div>
                  <div style={{textAlign: "center", zIndex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "26px", letterSpacing: "1.5px", background: "linear-gradient(90deg,#f6dd92,#e9c45e,#cda12f)", WebkitBackgroundClip: "text", backgroundClip: "text", WebkitTextFillColor: "transparent", color: "#e9c45e"}}>FC JAVIER</div><div style={{fontSize: "11px", color: "rgba(255,255,255,0.6)", marginTop: "4px"}}>2 competiciones activas · 150M</div></div>
                </div>
                <div style={{flex: "1", padding: "18px 16px", display: "flex", flexDirection: "column", gap: "10px", overflow: "hidden"}}>
                  <div style={{fontSize: "10px", fontWeight: "800", letterSpacing: "1.5px", color: "#6a6470", textTransform: "uppercase"}}>Mis competiciones</div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "15px", background: "linear-gradient(100deg,#231f12,#161318)", border: "1px solid #4a3d1a", borderRadius: "16px", boxShadow: "0 0 22px rgba(236,200,98,0.07)"}}>
                    <div style={{width: "46px", height: "46px", borderRadius: "13px", background: "linear-gradient(140deg,#f6dd92,#cda12f)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px", boxShadow: "0 4px 12px rgba(205,161,47,0.4)"}}>🏆</div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "18px", letterSpacing: "0.4px", color: "#f4f0e6"}}>Liga Neo</div><div style={{fontSize: "10px", color: "#b59a4e"}}>Ver mi alineación</div></div><span style={{fontSize: "20px", color: "#7a6a3a"}}>›</span>
                  </div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "15px", background: "linear-gradient(100deg,#16202e,#141318)", border: "1px solid #2c2935", borderRadius: "16px"}}>
                    <div style={{width: "46px", height: "46px", borderRadius: "13px", background: "linear-gradient(140deg,#2e6cb0,#0f3a66)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px"}}>⭐</div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "18px", letterSpacing: "0.4px", color: "#f4f0e6"}}>Champions EC</div><div style={{fontSize: "10px", color: "#8b94a4"}}>Ver mi alineación</div></div><span style={{fontSize: "20px", color: "#4a4754"}}>›</span>
                  </div>
                  <div style={{fontSize: "10px", fontWeight: "800", letterSpacing: "1.5px", color: "#6a6470", textTransform: "uppercase", marginTop: "6px"}}>Más</div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#141318", border: "1px solid #2c2935", borderRadius: "16px"}}>
                    <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#1d1b22", border: "1px solid #34313d", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px", position: "relative"}}>📰<span style={{position: "absolute", top: "-5px", right: "-5px", minWidth: "19px", height: "19px", background: "#e0483a", color: "#fff", borderRadius: "50%", fontSize: "10px", fontWeight: "800", display: "flex", alignItems: "center", justifyContent: "center", border: "2px solid #0a0a0c"}}>3</span></div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "17px", letterSpacing: "0.4px", color: "#f4f0e6"}}>Noticias</div><div style={{fontSize: "10px", color: "#e07b6e", fontWeight: "600"}}>¡Te mencionaron 3 veces!</div></div><span style={{fontSize: "20px", color: "#4a4754"}}>›</span>
                  </div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#141318", border: "1px solid #2c2935", borderRadius: "16px"}}>
                    <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#1d1b22", border: "1px solid #34313d", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px"}}>🌍</div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "17px", letterSpacing: "0.4px", color: "#f4f0e6"}}>Mundial</div><div style={{fontSize: "10px", color: "#8b8596"}}>Selecciones nacionales</div></div><span style={{fontSize: "20px", color: "#4a4754"}}>›</span>
                  </div>
                  <div style={{display: "flex", alignItems: "center", gap: "13px", padding: "14px", background: "#141318", border: "1px solid #2c2935", borderRadius: "16px"}}>
                    <div style={{width: "44px", height: "44px", borderRadius: "13px", background: "#1d1b22", border: "1px solid #34313d", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px"}}>👕</div>
                    <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "17px", letterSpacing: "0.4px", color: "#f4f0e6"}}>Mi Equipo</div><div style={{fontSize: "10px", color: "#8b8596"}}>Campo y plantilla</div></div><span style={{fontSize: "20px", color: "#4a4754"}}>›</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
      
          
          <div style={{display: "flex", flexDirection: "column", gap: "14px"}}>
            <div style={{display: "flex", alignItems: "center", gap: "10px"}}><span style={{fontSize: "13px", fontWeight: "700", color: "#3a352a"}}>Mi Equipo · Campo</span><span style={{fontSize: "10px", fontWeight: "700", color: "#e9c45e", background: "#1a1813", padding: "3px 9px", borderRadius: "20px"}}>Oscuro</span></div>
            <div style={{width: "342px", height: "740px", background: "#0a0a0c", borderRadius: "38px", border: "1px solid #26242c", boxShadow: "0 30px 70px rgba(0,0,0,0.4),0 0 0 1px rgba(236,200,98,0.04)", overflow: "hidden", display: "flex", flexDirection: "column", position: "relative"}}>
              <div style={{height: "46px", flexShrink: "0", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 26px", background: "#0a0a0c"}}>
                <span style={{fontSize: "13px", fontWeight: "700", color: "#f4f0e6"}}>9:41</span>
                <div style={{display: "flex", alignItems: "center", gap: "6px"}}><span style={{fontSize: "10px", fontWeight: "700", color: "#f4f0e6"}}>5G</span><div style={{width: "22px", height: "11px", border: "1.4px solid #f4f0e6", borderRadius: "3px", display: "flex", alignItems: "center", padding: "1.5px"}}><div style={{width: "70%", height: "100%", background: "#f4f0e6", borderRadius: "1px"}}></div></div></div>
              </div>
              <div className="fls-scr">
                <div style={{display: "flex", alignItems: "center", gap: "10px", padding: "12px 16px", borderBottom: "1px solid #1f1d24"}}>
                  <div style={{width: "32px", height: "32px", borderRadius: "10px", background: "#16151a", border: "1px solid #2c2935", display: "flex", alignItems: "center", justifyContent: "center", color: "#9690a0", fontSize: "18px"}}>‹</div>
                  <div style={{flex: "1"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "18px", letterSpacing: "0.5px", color: "#f4f0e6", lineHeight: "1"}}>MI EQUIPO</div><div style={{fontSize: "10px", color: "#8b8596"}}>Alineación · Liga</div></div>
                  <div style={{fontSize: "11px", fontWeight: "800", color: "#1a1205", background: "linear-gradient(90deg,#f6dd92,#d4af4a)", padding: "5px 10px", borderRadius: "9px"}}>4-3-3</div>
                  <div style={{width: "32px", height: "32px", borderRadius: "10px", background: "#16151a", border: "1px solid #2c2935", display: "flex", alignItems: "center", justifyContent: "center", color: "#9690a0", fontSize: "15px"}}>⚙</div>
                </div>
                <div style={{flex: "1", overflow: "hidden", padding: "12px 14px 0", display: "flex", flexDirection: "column", gap: "11px"}}>
                  <div style={{position: "relative", borderRadius: "18px", overflow: "hidden", height: "392px", background: "linear-gradient(180deg,#0c3a20,#0f4a29 50%,#0c3a20)", boxShadow: "inset 0 0 70px rgba(0,0,0,0.5),0 0 0 1px rgba(236,200,98,0.06)"}}>
                    <div style={{position: "absolute", inset: "0", background: "repeating-linear-gradient(180deg,rgba(236,200,98,0.03) 0 33px,rgba(0,0,0,0.12) 33px 66px)"}}></div>
                    <div style={{position: "absolute", left: "14px", right: "14px", top: "50%", height: "1.5px", background: "rgba(236,200,98,0.22)"}}></div>
                    <div style={{position: "absolute", left: "50%", top: "50%", width: "86px", height: "86px", border: "1.5px solid rgba(236,200,98,0.22)", borderRadius: "50%", transform: "translate(-50%,-50%)"}}></div>
                    <div style={{position: "absolute", left: "50%", top: "0", transform: "translateX(-50%)", width: "120px", height: "46px", border: "1.5px solid rgba(236,200,98,0.16)", borderTop: "none", borderRadius: "0 0 8px 8px"}}></div>
                    <div style={{position: "absolute", left: "50%", bottom: "0", transform: "translateX(-50%)", width: "120px", height: "46px", border: "1.5px solid rgba(236,200,98,0.16)", borderBottom: "none", borderRadius: "8px 8px 0 0"}}></div>
                    <div style={{position: "absolute", left: "50%", top: "87%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>89</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>COURTOIS</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>POR</div></div></div>
                    <div style={{position: "absolute", left: "80%", top: "69%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>85</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>HAKIMI</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>DFD</div></div></div>
                    <div style={{position: "absolute", left: "62%", top: "70%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>86</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>SALIBA</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>DFC</div></div></div>
                    <div style={{position: "absolute", left: "38%", top: "70%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>85</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>BASTONI</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>DFC</div></div></div>
                    <div style={{position: "absolute", left: "20%", top: "69%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>85</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>T. HDEZ</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>DFI</div></div></div>
                    <div style={{position: "absolute", left: "74%", top: "50%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>87</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>BELLINGHAM</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>MC</div></div></div>
                    <div style={{position: "absolute", left: "50%", top: "46%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "46px", height: "46px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #ecc862", boxShadow: "0 4px 14px rgba(236,200,98,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "18px", color: "#ecc862"}}>90</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #5a4a1d", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>RODRI</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>MC</div></div></div>
                    <div style={{position: "absolute", left: "26%", top: "50%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>88</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>PEDRI</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>MC</div></div></div>
                    <div style={{position: "absolute", left: "80%", top: "26%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>87</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>SAKA</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>ED</div></div></div>
                    <div style={{position: "absolute", left: "50%", top: "16%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "46px", height: "46px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #ecc862", boxShadow: "0 4px 14px rgba(236,200,98,0.4)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "18px", color: "#ecc862"}}>91</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #5a4a1d", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>HAALAND</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>DC</div></div></div>
                    <div style={{position: "absolute", left: "20%", top: "26%", transform: "translate(-50%,-50%)", display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", width: "64px"}}><div style={{width: "42px", height: "42px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2.5px solid #2c2935", boxShadow: "0 4px 10px rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "16px", color: "#ecc862"}}>90</span></div><div style={{background: "rgba(0,0,0,0.7)", border: "1px solid #2c2935", borderRadius: "5px", padding: "2px 7px", textAlign: "center", maxWidth: "64px"}}><div style={{fontFamily: "'Bebas Neue'", fontSize: "9px", color: "#f4f0e6", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>VINÍCIUS</div><div style={{fontSize: "7px", color: "#ecc862", fontWeight: "700"}}>EI</div></div></div>
                  </div>
                  <div style={{display: "flex", gap: "6px", overflow: "hidden"}}>
                    <div style={{fontSize: "11px", fontWeight: "800", color: "#1a1205", background: "linear-gradient(90deg,#f6dd92,#d4af4a)", padding: "5px 10px", borderRadius: "8px"}}>4-3-3</div>
                    <div style={{fontSize: "11px", fontWeight: "700", color: "#9690a0", background: "#16151a", border: "1px solid #2c2935", padding: "5px 10px", borderRadius: "8px"}}>4-2-3-1</div>
                    <div style={{fontSize: "11px", fontWeight: "700", color: "#9690a0", background: "#16151a", border: "1px solid #2c2935", padding: "5px 10px", borderRadius: "8px"}}>4-4-2</div>
                    <div style={{fontSize: "11px", fontWeight: "700", color: "#9690a0", background: "#16151a", border: "1px solid #2c2935", padding: "5px 10px", borderRadius: "8px"}}>3-5-2</div>
                  </div>
                  <div style={{background: "#141318", border: "1px solid #2c2935", borderRadius: "14px", padding: "11px 11px 13px"}}>
                    <div style={{display: "flex", alignItems: "center", gap: "8px", marginBottom: "9px"}}><div style={{width: "3px", height: "14px", background: "linear-gradient(180deg,#f6dd92,#cda12f)", borderRadius: "2px"}}></div><span style={{fontFamily: "'Bebas Neue'", fontSize: "13px", letterSpacing: "1.2px", color: "#f4f0e6"}}>BANCA</span><span style={{marginLeft: "auto", fontSize: "10px", fontWeight: "800", color: "#1a1205", background: "linear-gradient(90deg,#f6dd92,#d4af4a)", padding: "2px 8px", borderRadius: "20px"}}>4/7</span></div>
                    <div style={{display: "grid", gridTemplateColumns: "repeat(7,1fr)", gap: "6px"}}>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#1c1a22", border: "1px solid #2c2935", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2px solid #2c2935", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#ecc862"}}>86</span></div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#f4f0e6"}}>MAIGNAN</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#1c1a22", border: "1px solid #2c2935", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2px solid #2c2935", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#ecc862"}}>86</span></div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#f4f0e6"}}>DIAS</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#1c1a22", border: "1px solid #2c2935", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2px solid #2c2935", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#ecc862"}}>88</span></div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#f4f0e6"}}>VALVERDE</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#1c1a22", border: "1px solid #2c2935", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(140deg,#1a6bb5,#0f3a66)", border: "2px solid #2c2935", display: "flex", alignItems: "center", justifyContent: "center"}}><span style={{fontFamily: "'Bebas Neue'", fontSize: "11px", color: "#ecc862"}}>86</span></div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#f4f0e6"}}>MUSIALA</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#0f0e12", border: "1px dashed #34313d", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", border: "1.5px dashed #3e3a48", display: "flex", alignItems: "center", justifyContent: "center", color: "#3e3a48", fontSize: "15px"}}>+</div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#5e5868"}}>SUB 5</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#0f0e12", border: "1px dashed #34313d", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", border: "1.5px dashed #3e3a48", display: "flex", alignItems: "center", justifyContent: "center", color: "#3e3a48", fontSize: "15px"}}>+</div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#5e5868"}}>SUB 6</div></div>
                      <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", background: "#0f0e12", border: "1px dashed #34313d", borderRadius: "10px", padding: "7px 2px"}}><div style={{width: "32px", height: "32px", borderRadius: "50%", border: "1.5px dashed #3e3a48", display: "flex", alignItems: "center", justifyContent: "center", color: "#3e3a48", fontSize: "15px"}}>+</div><div style={{fontFamily: "'Bebas Neue'", fontSize: "7px", color: "#5e5868"}}>SUB 7</div></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      
        </div>
      
        <div data-slot="more"></div>
      </div>
  );
}
